### ISSUE TITLE
Will this project continue?

### ISSUE THREAD

**Issue by Zxilly** [john-peterson/bin-patch#7]
I test it with NFS20 on Windows 10 1903,and only when the .dll file was placed under the PATH folder,it works.
Windows 10 forbid the user to change the sys files,it needs permission from the TrustInstaller.
If you placed it under PATH folder,it will cause VAC warning in the CSGO.
Could you please update it to make it work when it was placed under the same folder with the exe file on Windows 10?

**Comment by john-peterson** [comment]
I don't know off hand how this affinity works. why would it have anything to do with the dll file. Windows always read them locally first since 1.0 I don't know if they changed it
________________________________

**Comment by Zxilly** [comment]
I download IDA and try to repeat the change you make on the Xinput.dll(win10 version),however,i failed.
Could you please make the same change with the latest dll file?
I can provide the file.
https://transfer.sh/J619d/XInput9_1_0.dll

**Comment by john-peterson** [comment]
I don't even have a Windows right now travelling. Internet café hate when you suck on their computers essentially everyone hates when you hack on their borrowed so i'm completely lost
________________________________
